load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "guava",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:com_google_guava_guava",
    ],
)

java_library(
    name = "apache-lang3",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_apache_commons_commons_lang3",
    ],
)
