load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "okhttp-client",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:com_squareup_okhttp3_okhttp",
    ],
)
