load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "time",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:joda_time_joda_time",
    ],
)

java_library(
    name = "convert",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_joda_joda_convert",
    ],
)

java_library(
    name = "money",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:org_joda_joda_money",
    ],
)
