load("@rules_java//java:defs.bzl", "java_import", "java_library", "java_plugin")

java_library(
    name = "objectify",
    visibility = ["//visibility:public"],
    exports = [
        "@maven//:com_googlecode_objectify_objectify",
        "@maven//:javax_servlet_javax_servlet_api",
        "@maven//:org_projectlombok_lombok",
    ],
)
